coverage:
  status:
    project:
      default: false

comment:
  layout: "header, diff, flags, components"

ignore:
  - "ref/asciidoc-lang/docs/modules/*/nav*.adoc"
  - "ref/asciidoc-lang/docs/modules/*/examples/**"
  - "ref/asciidoc-lang/docs/modules/*/partials/**"
  - "sdd/**"

component_management:
  default_rules:
    statuses:
      - type: project
  
  individual_components:
    - component_id: parser
      name: Parser test coverage
      paths:
        - parser/**
    
    - component_id: spec
      name: AsciiDoc spec coverage
      paths:
        - ref/asciidoc-lang/docs/modules/**
